name: 'Test'
description: 'Run tests for Node.js, Python, Go, or Bun projects'

inputs:
  project_type:
    description: 'The type of project (node, python, go, bun)'
    required: false
    default: 'node'
  node_version:
    description: 'The Node.js version to use'
    required: false
    default: 'latest'
  python_version:
    description: 'The Python version to use'
    required: false
    default: 'latest'
  go_version:
    description: 'The Go version to use'
    required: false
    default: 'latest'
  bun_version:
    description: 'The Bun version to use'
    required: false
    default: 'latest'
  run_lint:
    description: 'Whether to run linting'
    required: false
    default: 'true'
  working_directory:
    description: 'The directory to run tests in'
    required: false
    default: '.'

outputs:
  sha:
    description: 'The SHA that was tested'
    value: ${{ github.sha }}
  ref:
    description: 'The ref that was tested'
    value: ${{ github.ref }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      if: inputs.project_type == 'node'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'
    
    - name: Setup Python
      if: inputs.project_type == 'python'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'pip'
    
    - name: Setup Go
      if: inputs.project_type == 'go'
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go_version }}
        cache: true
    
    - name: Setup Bun
      if: inputs.project_type == 'bun'
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun_version }}
    
    - name: Install Dependencies
      shell: bash
      run: |
        cd ${{ inputs.working_directory }}
        if [ "${{ inputs.project_type }}" = "node" ]; then
          npm ci
        elif [ "${{ inputs.project_type }}" = "python" ]; then
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        elif [ "${{ inputs.project_type }}" = "go" ]; then
          go mod download
        elif [ "${{ inputs.project_type }}" = "bun" ]; then
          bun install
        fi
    
    - name: Run Tests
      shell: bash
      run: |
        cd ${{ inputs.working_directory }}
        if [ "${{ inputs.project_type }}" = "node" ]; then
          npm test
        elif [ "${{ inputs.project_type }}" = "python" ]; then
          python -m pytest
        elif [ "${{ inputs.project_type }}" = "go" ]; then
          go test ./...
        elif [ "${{ inputs.project_type }}" = "bun" ]; then
          bun test
        fi
    
    - name: Run Linting
      if: inputs.run_lint == 'true'
      shell: bash
      run: |
        cd ${{ inputs.working_directory }}
        if [ "${{ inputs.project_type }}" = "node" ]; then
          npm run lint
        elif [ "${{ inputs.project_type }}" = "python" ]; then
          pip install flake8
          flake8 .
        elif [ "${{ inputs.project_type }}" = "go" ]; then
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          if [ -f ".golangci.yml" ]; then
            golangci-lint run --config=.golangci.yml ./...
          else
            golangci-lint run ./...
          fi
        elif [ "${{ inputs.project_type }}" = "bun" ]; then
          bun run lint
        fi 